package-name: airflow-provider-carbonaware
display-name: CarbonAware
docs-url: https://github.com/carbon-aware/airflow-provider-carbon-aware/blob/main/README.md

operators:
  - module: carbonaware_provider.operators.carbonaware.CarbonAwareOperator
